### ISSUE TITLE
Document how to install for IntelliJ

### ISSUE THREAD

**Issue by ryanolsonx** [mtyn/polar#8]
I love the look of this theme. Can you please provide docs on how to install it to JetBrains products? Or submit to the JetBrains plugin store?

I'm having trouble getting it installed.

**Comment by mtyn** [comment]
Sure - documentation is generally lacking in this repo, sorry about that, it's on the todo list! 

I've submitted the theme to the JetBrains plugin marketplace, it's currently awaiting approval. According to their customer support it should only take a couple of days. In the meantime, I've attached a jar file of the latest build you can use to install it manually if you'd like.

To do this:
1. Extract the [attached zip](https://github.com/mtyn/polar/files/4814223/polar-1.0.2.jar.zip) to get the .jar file inside
2. Open the preferences menu inside your IDE of choice
3. Go to plugins
4. Click the gear icon next to the installed tab
5. Choose "Install Plugin From Disk"
6. Pick the jar file for the polar theme

I've tested it with WebStorm / IntelliJ / GoLand / AppCode / PyCharm / CLion, but I assume these instructions should work the same across any IDEA based IDE.

**Disclaimer**: If you do decide to manually install the plugin, I'm not sure how it will interact with the plugin from the plugin store once it arrives - you may need to manually uninstall the manually installed one in order to get the updates from the store (someone else please correct me on this if I'm mistaken, I'm very new to making JetBrains plugins!). 



Any feedback on the JetBrains plugin would be gratefully received - it's my first attempt at porting the new Nord Jetbrains UI theme across as a light theme, and I'm sure there's a few bits and pieces that might need fine tuning. 

I'll leave this issue open until I get some proper documentation sorted for installing each of the themes (most are straight forward enough, but some have a few steps)

**Comment by ryanolsonx** [comment]
Thank you so much! It installed well on WebStorm. I'll let you know if I have any feedback. I think I'm going to tweak some of the colors so that they are more accessible (mostly just darken some of them).

**Comment by ryanolsonx** [comment]
<img width="760" alt="Screen Shot 2020-06-23 at 9 39 40 AM" src="https://user-images.githubusercontent.com/238929/85424698-78a20680-b535-11ea-9c11-2b7c3253b300.png">
A good thing is that once it's installed manually, you can manage it like other plugins.

**Comment by mtyn** [comment]
Great! Glad you got it installed ok. The plugin has now been released on the plugin marketplace, so from now on any updates / further installations should be as simple as downloading the plugin from there, so I'll close this issue now. Any further issues let me know!
